name: follicles-detection
channels:
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - scikit-learn
  - pandas
  - jupyter
  - matplotlib-base
  - opencv
  - imageio
  - scipy
  - pytorch
  - cudatoolkit=10.2
  - torchvision

  # dev
  - black
  - flake8

  - pip
  - pip:
    - tensorflow==2.6.3
    - osfclient
    - ramp-workflow
